version : "3.7"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "alfa1uno"
      PGDATA: /vat/lib/postgresql/data/pgdata
    ports:
      - 15432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      postgres_network:
        aliases:
          - postgres_host
          
volumes:
  pgdata: {}
networks:
  postgres_network:
    name: postgres_net
    driver: bridge
